# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StandupBot < Formula
  desc "CLI tool for managing daily standup updates via GitHub"
  homepage "https://github.com/livelabs-ventures/go-bot"
  version "0.1.1"
  license "MIT"

  depends_on "gh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.1.1/go-bot_Darwin_x86_64.tar.gz"
      sha256 "ccda82864fd3c753940cceeb6bc6bceb86a2e512747971d2aa466063c3742974"

      def install
        bin.install "standup-bot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.1.1/go-bot_Darwin_arm64.tar.gz"
      sha256 "abcf3fe30c436184dbeb39aeb2d6ba70ab5ee59e0502afc89890fb0473d5a4ad"

      def install
        bin.install "standup-bot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.1.1/go-bot_Linux_x86_64.tar.gz"
      sha256 "80cb90ad7a07e63087c0739ca03a84662b277f0cbd5c35b6b0c15665ed586a8f"
      def install
        bin.install "standup-bot"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.1.1/go-bot_Linux_arm64.tar.gz"
      sha256 "a5dac08a615ffe58f113a8ca295a57bfc9d63e40881d912381b09742f5933772"
      def install
        bin.install "standup-bot"
      end
    end
  end

  def caveats
    <<~EOS
      The standup-bot requires GitHub CLI (gh) to be installed and authenticated.

      Install GitHub CLI:
        brew install gh

      Then authenticate:
        gh auth login

      Configure standup-bot:
        standup-bot --config
    EOS
  end

  test do
    system "#{bin}/standup-bot --version"
  end
end
