# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StandupBot < Formula
  desc "CLI tool for managing daily standup updates via GitHub"
  homepage "https://github.com/livelabs-ventures/go-bot"
  version "0.2.0"
  license "MIT"

  depends_on "gh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.2.0/go-bot_Darwin_x86_64.tar.gz"
      sha256 "87ee5979af7540c6d48ddff3b6bdd190786c6cb64ed820225c0cc366c225f97a"

      def install
        bin.install "standup-bot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.2.0/go-bot_Darwin_arm64.tar.gz"
      sha256 "16f8086d301cbf295bfde6f1cb1d9d86d0509e69a19b8b46caa19228d360d36f"

      def install
        bin.install "standup-bot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.2.0/go-bot_Linux_x86_64.tar.gz"
      sha256 "cd1206e7ea51898caceeb43b3a89f922f318462ad0e4bdb807c3bfb25a124306"
      def install
        bin.install "standup-bot"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/livelabs-ventures/go-bot/releases/download/v0.2.0/go-bot_Linux_arm64.tar.gz"
      sha256 "6e0abe75b6b1ba54ed64b718d62ebc425b4384498bba67706184364307dade2f"
      def install
        bin.install "standup-bot"
      end
    end
  end

  def caveats
    <<~EOS
      The standup-bot requires GitHub CLI (gh) to be installed and authenticated.

      Install GitHub CLI:
        brew install gh

      Then authenticate:
        gh auth login

      Configure standup-bot:
        standup-bot --config
    EOS
  end

  test do
    system "#{bin}/standup-bot --version"
  end
end
